### ISSUE TITLE
cursor:pointer como padrão

### ISSUE THREAD

**Issue by likid** [po-ui/po-style#298]
Na atualização para versão 6.8.0 o ponteiro padrão para a aplicação toda está como "pointer" quando deveria ser "default". Este problema é detectável na própria página do po-ui.

**Comment by likid** [comment]
Pelo que analisei, alteraram o cursor do mouse no :root e por isso ficou atribuído o pointer para toda a aplicação.

**Comment by alinelariguet** [comment]
Boa tarde @likid , já temos PR criada, na próxima segunda já vai estar publicada a correção.
link da PR: https://github.com/po-ui/po-style/pull/305

Obrigada por reportar!

**Comment by alinelariguet** [comment]
Já foi corrigido e publicado na v6.11.0.
